[project]
name = "lewidi-lib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "matplotlib",
    "pydantic-settings"
]

[project.scripts]
lewidi-plot = "metrics_plotter:main"
